# Priority Dispatch Codes
PDC = {
    0:  "Unknown",
    1:  "Abdominal Pain/Problems",
    2:  "Allergies/Envenomations",
    3:  "Animal Bites/Attacks",
    4:  "Assault/Sexual Assault",
    5:  "Back Pain",
    6:  "Breathing Problems",
    7:  "Burns",
    8:  "Carbon Monoxide/Inhalation/HAZMAT/CBRN",
    9:  "Cardiac or Respiratory Arrest/Death",
    10: "Chest Pain (Non-Traumatic)",
    11: "Choking",
    12: "Convulsions/Seizures",
    13: "Diabetic Problems",
    14: "Drowning (near)/Diving/SCUBA Accident",
    15: "Electrocution/Lightning",
    16: "Eye Problems/Injuries",
    17: "Falls",
    18: "Headache",
    19: "Heart Problems/AICD",
    20: "Heat/Cold Exposure",
    21: "Hemorrhage/Laceration",
    22: "Inaccessible Incident/Other Entrapments (Non-Vehicle)",
    23: "Overdose/Poisoning (Ingestion)",
    24: "Pregnancy/Childbirth/Miscarriage",
    25: "Psychiatric/Abnormal Behavior/Suicide Attempt",
    26: "Sick Person (Specific Diagnosis)",
    27: "Stab/Gunshot/Penetrating Trauma",
    28: "Stroke (CVA)/Transient Ischemic Attack (TIA)",
    29: "Traffic/Transportation Incidents",
    30: "Traumatic Injuries (Specific)",
    31: "Unconscious/Fainting (Near)",
    32: "Unknown Problem (Person Down)",
    33: "Transfer/Interfacility/Palliative Care",
    51: "Aircraft Emergency",
    52: "Fire Alarm",
    53: "Citizen Assist/Service Call",
    54: "Confined Space/Structure Collapse",
    55: "Electrical Hazard",
    56: "Elevator/Escalator Rescue",
    57: "Explosion",
    58: "Extrication/Entrapped",
    59: "Fuel Spill",
    60: "Gas Leak/Gas Odor",
    61: "HAZMAT",
    62: "High Angle Rescue",
    63: "Lightning Strike",
    64: "Marine Fire",
    65: "Mutual Aid/Assist Outside Agency",
    66: "Odor/Unknown",
    67: "Outside Fire",
    68: "Smoke Investigation",
    69: "Structure Fire",
    70: "Train and Rail Collision/Derailment",
    71: "Vehicle Fire",
    72: "Water Rescue",
    73: "Watercraft in Distress",
    74: "Suspicious Package",
    75: "Train and Rail Fire",
    76: "Bomb Threat",
    77: "Motor Vehicle Collision"
}